spring:
 application:
   name: backup-agent


security:
 token:
   default: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
   name: X-Auth-Token

login:
   username: wsp
   password: wspbackup
   role: USER
