spring:
 application:
   name: backup-agent

 rabbitmq:
   password: evoila
   user: evoila
   virtual-host: evoila
   addresses: localhost:5672

security:
 token:
   default: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
   name: X-Auth-Token

login:
   username: admin
   password: cloudfoundry
   role: USER


queue:
  exchange: backup-jobs
  routing-key: backup-jobs
  queue: backup-jobs

